data = getData()

passportKeys = {
  byr: function(value)
    return true
  end function,
  iyr: function(value)
    return true
  end function,
  eyr: function(value)
    return true
  end function,
  hgt: function(value)
    return true
  end function,
  hcl: function(value)
    return true
  end function,
  ecl: function(value)
    return true
  end function,
  pid: function(value)
    return true
  end function
}



?countValidPassports(data.input, passportKeys)